const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const store={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let users=store.get("nourUsers",[]);
if(!users.length){users=[{username:"admin",password:"admin123",role:"admin"}];store.set("nourUsers",users)}
let current=store.get("nourCurrent",null), projects=store.get("nourProjects",[]);
let theme=store.get("nourTheme",{brand:"Nour AI",logo:"N",accent:"#6d5dfc"});

function showView(id){$$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active")}
$$("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab,.tool").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tool).classList.add("active")});
$("#loginBtn").onclick=()=>$("#loginDialog").showModal();
$("#logoutBtn").onclick=()=>{current=null;store.set("nourCurrent",null);renderAuth()};
function renderAuth(){let role=current?.role||"guest";$("#userBadge").textContent=current?`${current.username} · ${role}`:"Gast";$("#loginBtn").classList.toggle("hidden",!!current);$("#logoutBtn").classList.toggle("hidden",!current);$("#adminNav").classList.toggle("hidden",role!=="admin");if(role!=="admin"&&$("#admin").classList.contains("active"))showView("home");renderUsers()}
function login(){let u=users.find(x=>x.username===$("#loginUsername").value&&x.password===$("#loginPassword").value);if(!u)return $("#loginMessage").textContent="Benutzername oder Passwort falsch.";current={username:u.username,role:u.role};store.set("nourCurrent",current);$("#loginDialog").close();renderAuth()}
function register(){let n=$("#loginUsername").value.trim(),p=$("#loginPassword").value;if(n.length<3||p.length<4)return $("#loginMessage").textContent="Mindestens 3 Zeichen beim Namen und 4 beim Passwort.";if(users.some(x=>x.username===n))return $("#loginMessage").textContent="Benutzername bereits vergeben.";users.push({username:n,password:p,role:"user"});store.set("nourUsers",users);$("#loginMessage").textContent="Konto erstellt. Du kannst dich jetzt anmelden."}
function createUser(){if(current?.role!=="admin")return;let n=$("#newUsername").value.trim(),p=$("#newPassword").value,r=$("#newRole").value;if(!n||!p)return alert("Name und Passwort eingeben.");if(users.some(x=>x.username===n))return alert("Benutzer existiert bereits.");users.push({username:n,password:p,role:r});store.set("nourUsers",users);renderUsers()}
function renderUsers(){if(!$("#userList")||current?.role!=="admin")return;$("#userList").innerHTML=users.map((u,i)=>`<div class="user-row"><span><b>${u.username}</b><br><small>${u.role}</small></span>${u.username==="admin"?"":`<button onclick="deleteUser(${i})">Löschen</button>`}</div>`).join("")}
function deleteUser(i){users.splice(i,1);store.set("nourUsers",users);renderUsers()}
function saveTheme(){theme={brand:$("#adminBrand").value||"Nour AI",logo:$("#adminLogo").value||"N",accent:$("#adminAccent").value};store.set("nourTheme",theme);applyTheme()}
function applyTheme(){$("#brandName").textContent=theme.brand;$("#logoBox").textContent=theme.logo;document.documentElement.style.setProperty("--accent",theme.accent);if($("#adminBrand")){$("#adminBrand").value=theme.brand;$("#adminLogo").value=theme.logo;$("#adminAccent").value=theme.accent}}
function resetApp(){if(confirm("Alle lokalen Daten löschen?")){localStorage.clear();location.reload()}}
function addProject(type,name){projects.unshift({type,name,date:new Date().toLocaleString("de-DE"),owner:current?.username||"Gast"});store.set("nourProjects",projects);renderProjects()}
function renderProjects(){$("#projectList").innerHTML=projects.length?projects.map(p=>`<div class="project-row card"><span><b>${p.name}</b><br><small>${p.type} · ${p.owner} · ${p.date}</small></span></div>`).join(""):"<p>Noch keine Projekte.</p>"}
function runAssistant(){let p=$("#assistantPrompt").value.trim();if(!p)return;let out=`NOUR AI PROJEKTPLAN\n\nIdee: ${p}\n\n1. Ziel definieren\n2. Zielgruppe und Stil festlegen\n3. Inhalte erzeugen\n4. Ergebnis testen\n5. Als Website, Bild, Sticker, Video-Storyboard oder Spiel exportieren\n\nHinweis: Für echte generative KI kann später eine API über einen sicheren Server verbunden werden.`;$("#assistantOut").textContent=out;addProject("Assistent",p.slice(0,45))}
function makeImageCard(){let c=$("#imageCanvas"),x=c.getContext("2d"),p=$("#imagePrompt").value||"Nour AI Bild",s=$("#imageStyle").value,g=x.createLinearGradient(0,0,1024,1024);g.addColorStop(0,theme.accent);g.addColorStop(1,"#111827");x.fillStyle=g;x.fillRect(0,0,1024,1024);x.fillStyle="rgba(255,255,255,.12)";for(let i=0;i<18;i++){x.beginPath();x.arc(Math.random()*1024,Math.random()*1024,20+Math.random()*120,0,Math.PI*2);x.fill()}x.textAlign="center";x.fillStyle="white";x.font="bold 70px Arial";wrapText(x,p,512,440,850,86);x.font="32px Arial";x.fillText(s+" · Nour AI",512,800);addProject("Bild",p)}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){let words=text.split(" "),line="";for(let n=0;n<words.length;n++){let test=line+words[n]+" ";if(ctx.measureText(test).width>maxWidth&&n>0){ctx.fillText(line,x,y);line=words[n]+" ";y+=lineHeight}else line=test}ctx.fillText(line,x,y)}
function makeSticker(){let c=$("#stickerCanvas"),x=c.getContext("2d"),t=$("#stickerText").value,e=$("#stickerEmoji").value,col=$("#stickerColor").value;x.clearRect(0,0,800,800);x.fillStyle=col;x.beginPath();x.arc(400,400,320,0,Math.PI*2);x.fill();x.lineWidth=32;x.strokeStyle="white";x.stroke();x.textAlign="center";x.fillStyle="white";x.font="170px Arial";x.fillText(e,400,365);x.font="bold 90px Arial";x.fillText(t,400,535);addProject("Sticker",t)}
function makeStoryboard(){let t=$("#videoTopic").value||"Mein Video",l=$("#videoLength").value,n=Math.max(3,Math.round(l/5));$("#videoOut").innerHTML=Array.from({length:n},(_,i)=>`<div class="project-row"><b>Szene ${i+1}</b><span>${i===0?"Starker Einstieg":i===n-1?"Abschluss und Aufruf":"Hauptinhalt zeigen"} · ca. ${Math.round(l/n)} Sek.</span></div>`).join("");addProject("Video-Storyboard",t)}
function downloadCanvas(id,name){let a=document.createElement("a");a.download=name;a.href=$("#"+id).toDataURL("image/png");a.click()}
function dl(name,text,type="text/html"){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadWebsite(){let n=$("#siteName").value,s=$("#siteSubtitle").value,t=$("#siteType").value,html=`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${n}</title><style>body{margin:0;font-family:Arial;background:#0d1020;color:white;display:grid;place-items:center;min-height:100vh;text-align:center}main{max-width:800px;padding:50px}h1{font-size:64px;margin:0}p{font-size:22px;color:#cbd5e1}.tag{color:#8b7cff}</style><main><div class="tag">${t}</div><h1>${n}</h1><p>${s}</p><button>Mehr erfahren</button></main></html>`;dl(n.replace(/\W+/g,"-")+".html",html);addProject("Website",n)}
function downloadGame(){let n=$("#gameName").value||"Nour Game",html=`<!doctype html><html><meta charset="utf-8"><title>${n}</title><style>body{margin:0;background:#101424;color:white;font-family:Arial;text-align:center}canvas{background:#191f35;max-width:100%;margin-top:20px}</style><h1>${n}</h1><p>Bewege dich mit ← → und fange die Münze.</p><canvas id="c" width="700" height="450"></canvas><script>let c=document.getElementById("c"),x=c.getContext("2d"),p=320,coin={x:100,y:20},score=0;onkeydown=e=>{if(e.key=="ArrowLeft")p-=35;if(e.key=="ArrowRight")p+=35};function f(){x.clearRect(0,0,700,450);coin.y+=4;if(coin.y>410&&Math.abs(coin.x-p)<70){score++;coin={x:30+Math.random()*640,y:0}}if(coin.y>450)coin={x:30+Math.random()*640,y:0};x.fillStyle="#8b7cff";x.fillRect(p,405,90,20);x.fillStyle="gold";x.beginPath();x.arc(coin.x,coin.y,15,0,7);x.fill();x.fillStyle="white";x.font="20px Arial";x.fillText("Punkte: "+score,20,30);requestAnimationFrame(f)}f()<\/script></html>`;dl(n.replace(/\W+/g,"-")+".html",html);addProject("Spiel",n)}
applyTheme();renderAuth();renderProjects();makeSticker();