let mode="chat",messages=[];const $=s=>document.querySelector(s);
function setMode(m){mode=m;$("#title").textContent=m==="chat"?"Nour AI":m==="image"?"Bild erstellen":"Website erstellen";$("#prompt").placeholder=m==="chat"?"Nachricht an Nour AI …":m==="image"?"Beschreibe das Bild …":"Beschreibe deine Website …"}
function newChat(){messages=[];$("#messages").innerHTML='<div class="welcome"><h1>Was möchtest du erstellen?</h1><p>Fragen stellen, Bilder erzeugen oder komplette Websites bauen.</p></div>';$("#result").innerHTML=""}
function add(role,text){$(".welcome")?.remove();let d=document.createElement("div");d.className="msg "+role;d.textContent=text;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
$("#composer").onsubmit=async e=>{e.preventDefault();let p=$("#prompt").value.trim();if(!p)return;$("#prompt").value="";add("user",p);$("#status").textContent="Nour AI arbeitet …";try{
 if(mode==="chat"){messages.push({role:"user",content:p});let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages})});let j=await r.json();if(!r.ok)throw Error(j.error);messages.push({role:"assistant",content:j.text});add("assistant",j.text)}
 if(mode==="image"){let r=await fetch("/api/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:p})});let j=await r.json();if(!r.ok)throw Error(j.error);$("#result").innerHTML=`<img src="${j.image}"><p><a download="nour-ai-bild.png" href="${j.image}"><button>Bild herunterladen</button></a></p>`;add("assistant","Bild wurde erstellt.")}
 if(mode==="website"){let r=await fetch("/api/website",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:p})});let j=await r.json();if(!r.ok)throw Error(j.error);let blob=new Blob([j.html],{type:"text/html"}),url=URL.createObjectURL(blob);$("#result").innerHTML=`<iframe src="${url}"></iframe><p><a download="nour-website.html" href="${url}"><button>Website herunterladen</button></a></p>`;add("assistant","Die Website wurde erstellt und kann unten geöffnet oder heruntergeladen werden.")}
}catch(err){add("assistant","Fehler: "+err.message)}finally{$("#status").textContent="Bereit"}};
